<h1> Assignment – 4: Numerical Computation with NumPy</h1>

**Aim**: Numerical Computation with NumPy, Perform different computations using

**Theory**:

NumPy (short for Numerical Python) is a foundational library for scientific and numerical computing in Python. It offers robust support for large, multi‑dimensional arrays and matrices, along with an extensive collection of mathematical functions designed for efficient, element‑wise operations.

In this assignment, NumPy arrays were created and manipulated to demonstrate core techniques such as indexing, slicing, and basic arithmetic computations. A two‑dimensional (2D) array was used to show how individual elements can be accessed via index positions, and how sub‑arrays (slices) can be extracted. NumPy’s design makes handling such structured data straightforward. Additionally, a one‑dimensional (1D) array was employed to perform common statistical operations—calculating squares, sums, and means—which are frequently encountered in data analysis.

Why is NumPy faster than pure Python?

It leverages vectorization, meaning operations are applied to entire arrays at once rather than looping over individual elements.

Its core routines are implemented in C, resulting in high execution speed.

Data is stored in contiguous memory blocks, which improves memory access patterns and computational efficiency.

NumPy supports a wide range of mathematical operations, including:

Arithmetic – addition, subtraction, multiplication, etc.

Statistical functions – mean, sum, standard deviation.

Advanced computations – linear algebra (matrix multiplication, determinants), trigonometric functions, and more.

Its powerful indexing and slicing capabilities allow users to access and modify specific portions of data without unnecessary copying.

Finally, NumPy serves as the underpinning for most other Python data science libraries, including:

Pandas (data wrangling and analysis)

Matplotlib (visualisation)

Scikit‑learn (machine learning)


In [ ]:
import numpy as np

arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("2D Array:\n", arr_2d)

print("\nElement at index [1, 2]:", arr_2d[1, 2]) # Output: 60

print("\nSliced Sub-array:\n", arr_2d[0:2, 1:3])

arr = np.array([1, 2, 3, 4])
print("\nOriginal Array:", arr)
print("Square of Array:", np.square(arr))
print("Sum of elements:", np.sum(arr))
print("Mean value:", np.mean(arr))

2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at index [1, 2]: 60

Sliced Sub-array:
 [[20 30]
 [50 60]]

Original Array: [1 2 3 4]
Square of Array: [ 1  4  9 16]
Sum of elements: 10
Mean value: 2.5


**1. Role of NumPy in Scientific Computing**

NumPy is a Python library used for scientific and numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to perform efficient operations on these arrays.

  1. Support for large, multi-dimensional arrays and matrices.

  2. A large collection of high-level mathematical functions to operate on these arrays.

  3. The foundational data structure used by almost all other data science libraries like Pandas, Scikit-learn, and Matplotlib.




<br>



<br>



**2. Why is NumPy faster than Pure Python?**

NumPy is significantly faster for numerical operations because:

  1. Vectorization: It performs operations on entire arrays at once without needing explicit for loops in Python.

  2. C-Implementation: Its core functions are written in C, which allows for highly optimized, low-level execution.

  3. Contiguous Memory: NumPy arrays are stored in a continuous block of memory, making access much faster than Python lists.


**3. Mathematical Operations in NumPy**

NumPy supports a wide range of operations:

  1. Arithmetic: Addition, subtraction, multiplication, division.

  2. Linear Algebra: Matrix multiplication, dot products, determinants, and inverses.

  3. Statistics: Mean, median, standard deviation, and variance.

  4. Trigonometry: Sine, cosine, tangent, etc.

**4. NumPy Basics & Operations**
NumPy Basics & Operations (in NumPy):

NumPy provides efficient ways to work with numerical data using arrays and supports a wide range of mathematical operations.

1. Array Creation:
NumPy allows creation of arrays from lists or built-in methods.
These arrays can be 1D, 2D, or multi-dimensional.

2. Types of Arrays:
* 1D arrays: single row or column of elements
* 2D arrays: rows and columns (like a matrix)
* Multi-dimensional arrays: used for complex data structures

3. Basic Operations:
Performs element-wise arithmetic operations such as addition, subtraction, multiplication, and division
Supports operations between two arrays of the same shape

4. Indexing and Slicing:
Allows accessing specific elements or a range of elements from an array.
Helps in extracting required portions of data

**5. NumPy Integration with Other Libraries:**

NumPy plays a central role in Python’s data science ecosystem and acts as the core “engine” for many important libraries.

1. Pandas: Uses NumPy arrays internally to store and manage data efficiently in DataFrames.

2. Matplotlib: Relies on NumPy arrays to handle numerical data for plotting graphs and charts.

3. Scikit-learn: Requires data in the form of NumPy arrays for training and testing machine learning models.


**Conclusion**:

This assignment demonstrates how NumPy can be used for efficient numerical computation and data manipulation. Arrays were created, accessed, and processed using various operations such as slicing, mathematical functions, and statistical calculations.
